In [2]:
import pandas as pd
import numpy as np

In [3]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis =1 )

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
np.concatenate([arr1, arr1])
# np.concatenate([arr1, arr1], axis =0 )

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
ser1 = pd.Series([0,1,2], index = list('TUV'))

ser2 = pd.Series([3,4], index = ['X', 'Y'])

In [11]:
ser1

T    0
U    1
V    2
dtype: int64

In [12]:
ser2

X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [14]:
pd.concat([ser1, ser2], axis = 1)

C:\Users\82102\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [15]:
pd.concat([ser1, ser2], keys = ['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [16]:
dframe1 = pd.DataFrame(np.random.randn(4,3), columns = list('XYZ'))

dframe2 = pd.DataFrame(np.random.randn(3,3), columns = list('YQX'))

In [17]:
dframe1

X         Y         Z
0  1.899202  0.229965 -1.096288
1  0.238981  1.533468  0.730922
2  1.159842  0.479219 -1.320397
3 -0.174060 -1.651809  1.365786

In [18]:
dframe2

Y         Q         X
0  0.16396  1.029019 -0.832181
1  0.93256  1.118844  0.801232
2  1.50658  0.361304  0.646223

In [19]:
pd.concat([dframe1, dframe2])

C:\Users\82102\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  1.899202  0.229965 -1.096288
1       NaN  0.238981  1.533468  0.730922
2       NaN  1.159842  0.479219 -1.320397
3       NaN -0.174060 -1.651809  1.365786
0  1.029019 -0.832181  0.163960       NaN
1  1.118844  0.801232  0.932560       NaN
2  0.361304  0.646223  1.506580       NaN

In [20]:
pd.concat([dframe1, dframe2], axis = 1)

X         Y         Z        Y         Q         X
0  1.899202  0.229965 -1.096288  0.16396  1.029019 -0.832181
1  0.238981  1.533468  0.730922  0.93256  1.118844  0.801232
2  1.159842  0.479219 -1.320397  1.50658  0.361304  0.646223
3 -0.174060 -1.651809  1.365786      NaN       NaN       NaN

In [22]:
pd.concat([dframe1, dframe2], axis = 1, keys = ['df1', 'df2'])

df1                          df2                    
          X         Y         Z        Y         Q         X
0  1.899202  0.229965 -1.096288  0.16396  1.029019 -0.832181
1  0.238981  1.533468  0.730922  0.93256  1.118844  0.801232
2  1.159842  0.479219 -1.320397  1.50658  0.361304  0.646223
3 -0.174060 -1.651809  1.365786      NaN       NaN       NaN

In [25]:
pd.concat([dframe1, dframe2], ignore_index = True)
# set the index again

C:\Users\82102\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


Q         X         Y         Z
0       NaN  1.899202  0.229965 -1.096288
1       NaN  0.238981  1.533468  0.730922
2       NaN  1.159842  0.479219 -1.320397
3       NaN -0.174060 -1.651809  1.365786
4  1.029019 -0.832181  0.163960       NaN
5  1.118844  0.801232  0.932560       NaN
6  0.361304  0.646223  1.506580       NaN

In [27]:
# df.concat(): https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.concat.html