In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
np.exp(arr)
# e^ arr

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [15]:
A = np.random.randn(10)
A

array([ 0.55698647, -0.30635698,  0.43907748,  0.06661847,  1.27757153,
        0.49025566, -1.23164845, -1.09265934,  1.05982415, -0.7948167 ])

In [17]:
B = np.random.randn(10)
B

array([ 2.01528198,  0.59097035,  0.53461353,  0.37515206, -0.01742478,
       -0.64097448, -1.45662966,  0.02382515, -0.32355736,  0.7332924 ])

In [19]:
# Binary Functions
np.add(A,B)
# add every elements in same spot

array([ 2.57226845,  0.28461336,  0.97369101,  0.44177053,  1.26014675,
       -0.15071882, -2.68827811, -1.0688342 ,  0.7362668 , -0.06152431])

In [21]:
np.maximum(A,B)
# find the maximum value in same spot

array([ 2.01528198,  0.59097035,  0.53461353,  0.37515206,  1.27757153,
        0.49025566, -1.23164845,  0.02382515,  1.05982415,  0.7332924 ])

In [22]:
np.minimum(A,B)

array([ 0.55698647, -0.30635698,  0.43907748,  0.06661847, -0.01742478,
       -0.64097448, -1.45662966, -1.09265934, -0.32355736, -0.7948167 ])

In [23]:
# http://docs.scipy.org/doc/numpy/reference/ufuncs.html#avaiable-ufuncs
# more functions for Numpy

In [32]:
np.sin(A)
# randians

array([ 0.52863056, -0.30158725,  0.42510464,  0.0665692 ,  0.95731676,
        0.47085145, -0.94303849, -0.88785369,  0.8722695 , -0.71373523])